# Generated by Django 3.1.5 on 2021-05-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name="Nom d'Equipe"),
        ),
    ]
