# Generated by Django 3.1.5 on 2021-04-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_number',
            field=models.CharField(max_length=3, unique=True, verbose_name='numéro de département'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=240, unique=True, verbose_name='Département'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=240, unique=True, verbose_name='Région'),
        ),
    ]
