# Generated by Django 3.1.5 on 2021-05-29 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_auto_20210523_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_city', to='communities.department', verbose_name='Département'),
        ),
        migrations.AlterField(
            model_name='city',
            name='intercom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercom_city', to='communities.intercom', verbose_name='Intercommunalité'),
        ),
    ]
