# Generated by Django 3.1.5 on 2021-04-22 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_auto_20210422_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercom',
            name='department',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='communities.department', verbose_name='Département'),
        ),
    ]
