# Generated by Django 3.1.5 on 2021-04-22 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_intercom_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='department',
            field=models.ForeignKey(default='14', on_delete=django.db.models.deletion.CASCADE, to='communities.department', verbose_name='Département'),
        ),
        migrations.AlterField(
            model_name='city',
            name='intercom',
            field=models.ForeignKey(default='4', on_delete=django.db.models.deletion.CASCADE, to='communities.intercom', verbose_name='Intercommunalité'),
        ),
        migrations.AlterField(
            model_name='intercom',
            name='department',
            field=models.ForeignKey(default='14', on_delete=django.db.models.deletion.CASCADE, to='communities.department', verbose_name='Département'),
        ),
    ]
