# Generated by Django 3.1.5 on 2021-04-25 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_auto_20210422_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='department',
            field=models.ForeignKey(default='14', on_delete=django.db.models.deletion.CASCADE, to='communities.department', verbose_name='Département'),
        ),
    ]
