# Generated by Django 3.1.5 on 2021-05-02 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0007_auto_20210427_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='intercom',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name']},
        ),
    ]
