# Generated by Django 3.1.5 on 2021-05-07 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0009_auto_20210507_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='communities.region'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.department', verbose_name='Département'),
        ),
        migrations.AlterField(
            model_name='city',
            name='intercom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.intercom', verbose_name='Intercommunalité'),
        ),
    ]
