# Generated by Django 3.1.5 on 2021-04-12 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Veuillez entrer un numéro Français', max_length=14, validators=[django.core.validators.RegexValidator(message='Veuillez entrer un numéro Français', regex='^(?:\\+|00)33|0)\\s*[1-9](?:[\\s.-]*\\d{2}){4}$')], verbose_name='Numéro de Téléphone'),
        ),
    ]
