# Generated by Django 3.1.5 on 2021-04-12 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='team',
            field=models.CharField(choices=[('STB1', 'Strasbourg-Ville'), ('STBN', 'Strasbourg-Neuhof'), ('MLHC', 'Mulhouse-Centre'), ('HGN', 'Haguenau')], default='STB1', max_length=4),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Veuillez entrer un numéro Français', max_length=14, validators=[django.core.validators.RegexValidator(message='Veuillez entrer un numéro valide', regex='^(?:(?:\\+|00)33|0)\\s*[1-9](?:[\\s.-]*\\d{2}){4}$')], verbose_name='Numéro de Téléphone'),
        ),
    ]
