# Generated by Django 3.1.5 on 2021-05-10 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20210510_0613'),
        ('accounts', '0002_auto_20210510_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='team',
            field=models.ForeignKey(default='Non Renseigné', on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Equipe'),
        ),
    ]
