# Generated by Django 3.1.5 on 2021-04-13 08:42

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210412_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
            ],
            options={
                'permissions': [('accounts.add_user', 'can add user')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Veuillez entrer un numéro Français', max_length=14, validators=[django.core.validators.RegexValidator(message='Veuillez entrer un numéro valide', regex='^(?:(?:\\+|00)33|0)\\s*[1-9](?:[\\s.-]*\\d{2}){4}$')], verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='team',
            field=models.CharField(choices=[('STB1', 'Strasbourg-Ville'), ('STBN', 'Strasbourg-Neuhof'), ('MLHC', 'Mulhouse-Centre'), ('HGN', 'Haguenau')], default='STB1', max_length=4, verbose_name='Equipe'),
        ),
    ]
