# Generated by Django 3.1.5 on 2021-05-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210511_0428'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.CharField(choices=[('Non Salarié', 'Non Salarié'), ('Manager', 'Manager'), ('Coordonnateur', 'Coordonnateur')], default='Non Salarié', max_length=20, verbose_name='Position'),
        ),
    ]
