# Generated by Django 3.1.5 on 2021-04-14 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210413_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteer',
            options={'permissions': [('can_view_interview', "consulter une fiche d'entretien")]},
        ),
    ]
