# Generated by Django 3.1.5 on 2021-04-17 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210414_0706'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Types',
            new_name='StatusType',
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'permissions': [('communities.add_intercom', 'ajouter intercommunalité')]},
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'permissions': [('view_interview', "consulter une fiche d'entretien")]},
        ),
    ]
