# Generated by Django 3.1.5 on 2021-04-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210417_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='type',
        ),
        migrations.AddField(
            model_name='customuser',
            name='status_type',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee'), ('VOLUNTEER', 'Volunteer')], default='VOLUNTEER', max_length=50, verbose_name='Statut'),
        ),
    ]
