# Generated by Django 3.1.5 on 2021-04-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210417_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status_type',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('EMPLOYEE', 'Employé'), ('VOLUNTEER', 'Bénévole')], default='VOLUNTEER', max_length=50, verbose_name='Statut'),
        ),
    ]
