# Generated by Django 3.1.5 on 2021-04-17 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210417_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('view_list_regions', 'voir liste des collectivités')]},
        ),
    ]
