# Generated by Django 3.1.5 on 2021-04-15 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('officials', '0001_initial'),
        ('accounts', '0006_auto_20210414_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvocacyTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_statement', models.CharField(max_length=240, verbose_name='Phrases Clé')),
                ('source', models.URLField(blank=True, max_length=240, verbose_name='Lien vers la source')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_planned', models.DateField(verbose_name='Date prévue')),
                ('date_effective', models.DateField(verbose_name='Date de réalisation')),
                ('status', models.CharField(choices=[('PDG', 'Interview Prévue'), ('XED', 'Interview Annulée'), ('DON', 'Interview Réalisée')], default='PDG', max_length=3, verbose_name="Statut de l'interview")),
                ('goal', models.CharField(max_length=420, verbose_name='Objectifs')),
                ('outcome', models.CharField(default="Résultats de l'interview", max_length=420, verbose_name='Résultats')),
                ('assessment', models.CharField(choices=[('100PC', 'Objectif Totalement Atteint'), ('75PC', 'Objectif Largement Atteint'), ('50PC', 'Objectif à Moitié Atteint'), ('25PC', "Atteinte limitée de l'Objectif"), ('0PC', "Echec de l'Entretien"), ('TBD', 'Non Renseigné')], default='TBD', max_length=5, verbose_name="Evaluation de l'entretien")),
                ('comments', models.CharField(blank=True, default='Non Renseigné', max_length=420, verbose_name='Commentaires')),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officials.official')),
                ('topics', models.ManyToManyField(to='interviews.AdvocacyTopic')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.volunteer')),
            ],
        ),
    ]
