# Generated by Django 3.1.5 on 2021-05-20 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('officials', '0006_auto_20210516_0946'),
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='comments',
            field=models.CharField(blank=True, max_length=420, verbose_name='Commentaires'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='goal',
            field=models.CharField(max_length=420, verbose_name='Objectif'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='official',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officials.official', verbose_name='Elu'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='outcome',
            field=models.CharField(blank=True, max_length=420, null=True, verbose_name='Résultats'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='topics',
            field=models.ManyToManyField(to='interviews.AdvocacyTopic', verbose_name='Thèmes'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.volunteer', verbose_name='Bénévole'),
        ),
    ]
