# Generated by Django 3.1.5 on 2021-05-29 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.volunteer', verbose_name='Bénévole'),
        ),
    ]
