# Generated by Django 3.1.5 on 2021-05-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_auto_20210520_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='topics',
            field=models.ManyToManyField(blank=True, to='interviews.AdvocacyTopic', verbose_name='Thèmes'),
        ),
    ]
