# Generated by Django 3.1.5 on 2021-05-12 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interviews', '0002_auto_20210512_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocacytopic',
            name='quote',
            field=models.CharField(blank=True, max_length=480, null=True, verbose_name='Citation'),
        ),
        migrations.AlterField(
            model_name='advocacytopic',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Rédacteur'),
        ),
        migrations.AlterField(
            model_name='advocacytopic',
            name='creation_date',
            field=models.DateField(auto_now_add=True, verbose_name='Date de Création'),
        ),
        migrations.AlterField(
            model_name='advocacytopic',
            name='updated_date',
            field=models.DateField(auto_now=True, verbose_name='Date de Mise à Jour'),
        ),
    ]
