# Generated by Django 3.1.5 on 2021-05-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_auto_20210512_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocacytopic',
            name='key_statement',
            field=models.CharField(max_length=240, verbose_name='Phrase Clé'),
        ),
    ]
