# Generated by Django 3.1.5 on 2021-05-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_auto_20210512_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocacytopic',
            name='is_active',
            field=models.BooleanField(null=True, verbose_name='Thème actif'),
        ),
        migrations.AddField(
            model_name='advocacytopic',
            name='keyword',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mot-Clé'),
        ),
    ]
