# Generated by Django 3.1.5 on 2021-05-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_auto_20210513_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocacytopic',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique_for_date='creation_date'),
        ),
    ]
