# Generated by Django 3.1.5 on 2021-05-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0006_advocacytopic_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocacytopic',
            name='source_title',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Titre de la Source'),
        ),
    ]
