# Generated by Django 3.1.5 on 2021-05-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0007_advocacytopic_source_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='advocacytopic',
            name='keyword',
            field=models.CharField(blank=True, choices=[('Emploi', 'Emploi'), ('Formation', 'Formation'), ('Migrations', 'Migrations'), ('Logement', 'Logement'), ('Ecologie', 'Ecologie'), ('Pauvreté', 'Pauvreté')], default=None, max_length=20, null=True, verbose_name='Mot-Clé'),
        ),
    ]
