# Generated by Django 3.1.5 on 2021-05-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0008_auto_20210514_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocacytopic',
            name='quote',
            field=models.TextField(blank=True, max_length=480, null=True, verbose_name='Citation'),
        ),
    ]
