# Generated by Django 3.1.5 on 2021-05-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0009_auto_20210515_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocacytopic',
            name='quote',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Citation'),
        ),
    ]
