# Generated by Django 3.1.5 on 2021-05-22 11:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MandateCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.CharField(choices=[('1975', '1975'), ('1976', '1976'), ('1977', '1977'), ('1978', '1978'), ('1979', '1979'), ('1980', '1980'), ('1981', '1981'), ('1982', '1982'), ('1983', '1983'), ('1984', '1984'), ('1985', '1985'), ('1986', '1986'), ('1987', '1987'), ('1988', '1988'), ('1989', '1989'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029')], max_length=4, verbose_name='Année de Début de Mandat')),
                ('function', models.CharField(choices=[('MAIRE', 'Maire'), ('ADJOINT', 'Adjoint au Maire'), ('COUNS', 'Conseiller Municipal'), ('UNK', 'Non Renseigné')], default='UNK', max_length=7, verbose_name='Fonction Occupée')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.city')),
            ],
        ),
        migrations.CreateModel(
            name='MandateDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.CharField(choices=[('1975', '1975'), ('1976', '1976'), ('1977', '1977'), ('1978', '1978'), ('1979', '1979'), ('1980', '1980'), ('1981', '1981'), ('1982', '1982'), ('1983', '1983'), ('1984', '1984'), ('1985', '1985'), ('1986', '1986'), ('1987', '1987'), ('1988', '1988'), ('1989', '1989'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029')], max_length=4, verbose_name='Année de Début de Mandat')),
                ('function', models.CharField(choices=[('Président', 'Président'), ('Vice-Président', 'Vice-Président'), ('Conseiller', 'Conseiller'), ('UNK', 'Non Renseigné')], default='UNK', max_length=14, verbose_name='Fonction Occupée')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.department')),
            ],
        ),
        migrations.CreateModel(
            name='MandateInterCom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.CharField(choices=[('1975', '1975'), ('1976', '1976'), ('1977', '1977'), ('1978', '1978'), ('1979', '1979'), ('1980', '1980'), ('1981', '1981'), ('1982', '1982'), ('1983', '1983'), ('1984', '1984'), ('1985', '1985'), ('1986', '1986'), ('1987', '1987'), ('1988', '1988'), ('1989', '1989'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029')], max_length=4, verbose_name='Année de Début de Mandat')),
                ('function', models.CharField(choices=[('CHAIR', 'Président'), ('VCHAIR', 'Vice-Président'), ('COUNS', 'Conseiller'), ('UNK', 'Non Renseigné')], default='UNK', max_length=6, verbose_name='Fonction Occupée')),
                ('intercom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.intercom')),
            ],
        ),
        migrations.CreateModel(
            name='MandateRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.CharField(choices=[('1975', '1975'), ('1976', '1976'), ('1977', '1977'), ('1978', '1978'), ('1979', '1979'), ('1980', '1980'), ('1981', '1981'), ('1982', '1982'), ('1983', '1983'), ('1984', '1984'), ('1985', '1985'), ('1986', '1986'), ('1987', '1987'), ('1988', '1988'), ('1989', '1989'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029')], max_length=4, verbose_name='Année de Début de Mandat')),
                ('function', models.CharField(choices=[('CHAIR', 'Président'), ('VCHAIR', 'Vice-Président'), ('COUNS', 'Conseiller'), ('UNK', 'Non Renseigné')], default='UNK', max_length=6, verbose_name='Fonction Occupée')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.region')),
            ],
        ),
        migrations.CreateModel(
            name='MPMandate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date de Début de Mandat')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.department')),
            ],
        ),
        migrations.CreateModel(
            name='SenatorMandate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.CharField(choices=[('1975', '1975'), ('1976', '1976'), ('1977', '1977'), ('1978', '1978'), ('1979', '1979'), ('1980', '1980'), ('1981', '1981'), ('1982', '1982'), ('1983', '1983'), ('1984', '1984'), ('1985', '1985'), ('1986', '1986'), ('1987', '1987'), ('1988', '1988'), ('1989', '1989'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029')], max_length=4, verbose_name='Année de Début de Mandat')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.department', verbose_name='Département')),
            ],
        ),
        migrations.CreateModel(
            name='Official',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=240, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=240, verbose_name='Nom')),
                ('influence_level', models.CharField(choices=[('0-INF', 'Aucune influence'), ('1-INF', "Peu d'influence"), ('2-INF', 'Influence moyenne'), ('3-INF', 'Influence élevée'), ('4-INF', 'Influence très élevée')], default='2-INF', max_length=5, verbose_name='Influence')),
                ('propinquity_level', models.CharField(choices=[('0-PROPINQ', 'Idées incompatibles'), ('1-PROPINQ', 'Idées presque compatibles'), ('2-PROPINQ', 'Idées compatibles'), ('3-PROPINQ', 'Idées proches'), ('4-PROPINQ', 'Mêmes idées'), ('UNK-PROPINQ', 'Idées inconnues')], default='UNK-PROPINQ', max_length=11, verbose_name='proximité')),
                ('attached_volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.volunteer', verbose_name='Bénévole dédié')),
                ('mandate_city', models.ManyToManyField(blank=True, to='officials.MandateCity')),
                ('mandate_department', models.ManyToManyField(blank=True, to='officials.MandateDepartment')),
                ('mandate_intercom', models.ManyToManyField(blank=True, to='officials.MandateInterCom')),
                ('mandate_region', models.ManyToManyField(blank=True, to='officials.MandateRegion')),
                ('mp_mandate', models.ManyToManyField(blank=True, to='officials.MPMandate')),
                ('senator_mandate', models.ManyToManyField(blank=True, to='officials.SenatorMandate')),
            ],
        ),
        migrations.AddConstraint(
            model_name='senatormandate',
            constraint=models.UniqueConstraint(fields=('department', 'start_year'), name='unique_mandate_department'),
        ),
    ]
