# Generated by Django 3.1.5 on 2021-04-14 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_auto_20210414_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Official',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=240, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=240, verbose_name='Nom')),
                ('influence_level', models.CharField(choices=[('0-INF', 'Aucune influence'), ('1-INF', "Peu d'influence"), ('2-INF', 'Influence moyenne'), ('3-INF', 'Influence élevée'), ('4-INF', 'Influence très élevée')], default='2-INF', max_length=5, verbose_name='Influence')),
                ('propinquity_level', models.CharField(choices=[('0-PROPINQ', 'Idées incompatibles'), ('1-PROPINQ', 'Idées presque compatibles'), ('2-PROPINQ', 'Idées compatibles'), ('3-PROPINQ', 'Idées proches'), ('4-PROPINQ', 'Mêmes idées'), ('UNK-PROPINQ', 'Idées inconnues')], default='UNK-PROPINQ', max_length=11, verbose_name='proximité')),
                ('attached_volunteer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.volunteer', verbose_name='Bénévole dédié')),
            ],
        ),
    ]
