# Generated by Django 3.1.5 on 2021-05-16 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mandateintercom',
            name='official',
        ),
        migrations.AddField(
            model_name='official',
            name='mandate_intercom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='officials.mandateintercom'),
        ),
    ]
