# Generated by Django 3.1.5 on 2021-05-15 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210514_1650'),
        ('officials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='official',
            name='intercoms',
        ),
        migrations.AlterField(
            model_name='official',
            name='attached_volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.volunteer', verbose_name='Bénévole dédié'),
        ),
    ]
