# Generated by Django 3.1.5 on 2021-04-17 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        ('officials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MandateInterCom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date de Début de Mandat')),
                ('function', models.CharField(choices=[('CHAIR', 'Président'), ('VCHAIR', 'Vice-Président'), ('COUNS', 'Conseiller'), ('UNK', 'Non Renseigné')], default='UNK', max_length=6, verbose_name='Fonction Occupée')),
                ('intercom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.intercom')),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officials.official')),
            ],
        ),
        migrations.AddField(
            model_name='official',
            name='intercoms',
            field=models.ManyToManyField(through='officials.MandateInterCom', to='communities.Intercom'),
        ),
    ]
