# Generated by Django 3.1.5 on 2021-05-23 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_auto_20210523_0725'),
        ('officials', '0002_auto_20210522_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandatecity',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='communities.department', verbose_name='Département'),
        ),
        migrations.AddField(
            model_name='mandatecity',
            name='intercom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='communities.intercom', verbose_name='Intercommunalité'),
        ),
        migrations.AddField(
            model_name='mandateintercom',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='communities.department', verbose_name='Département'),
        ),
        migrations.AlterField(
            model_name='mandatecity',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='communities.city', verbose_name='Commune'),
        ),
        migrations.AlterField(
            model_name='mandatedepartment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='communities.department', verbose_name='Département'),
        ),
        migrations.AlterField(
            model_name='mandateintercom',
            name='intercom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='communities.intercom', verbose_name='Intercommunalité'),
        ),
        migrations.AlterField(
            model_name='mandateregion',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='communities.region'),
        ),
        migrations.AlterField(
            model_name='mpmandate',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='communities.department'),
        ),
        migrations.AlterField(
            model_name='senatormandate',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='senator_mandate', to='communities.department', verbose_name='Département'),
        ),
    ]
