# Generated by Django 3.1.5 on 2021-05-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0002_auto_20210515_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandatecity',
            name='function',
            field=models.CharField(choices=[('MAIRE', 'Maire'), ('ADJOINT', 'Adjoint au Maire'), ('COUNS', 'Conseiller Municipal'), ('UNK', 'Non Renseigné')], default='UNK', max_length=7, verbose_name='Fonction Occupée'),
        ),
    ]
