# Generated by Django 3.1.5 on 2021-05-16 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0002_auto_20210516_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mandatecity',
            name='official',
        ),
        migrations.RemoveField(
            model_name='mandatedepartment',
            name='official',
        ),
        migrations.RemoveField(
            model_name='mandateregion',
            name='official',
        ),
        migrations.RemoveField(
            model_name='nationalmandate',
            name='official',
        ),
        migrations.AddField(
            model_name='official',
            name='mandate_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='officials.mandatecity'),
        ),
        migrations.AddField(
            model_name='official',
            name='mandate_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='officials.mandatedepartment'),
        ),
        migrations.AddField(
            model_name='official',
            name='mandate_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='officials.mandateregion'),
        ),
        migrations.AddField(
            model_name='official',
            name='national_mandate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='officials.nationalmandate'),
        ),
    ]
