# Generated by Django 3.1.5 on 2021-04-17 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        ('officials', '0002_auto_20210417_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalMandate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date de Début de Mandat')),
                ('function', models.CharField(choices=[('MP', 'Député'), ('SEN', 'Sénateur'), ('UNK', 'Non Renseigné')], default='UNK', max_length=6, verbose_name='Mandat National')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.department')),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officials.official')),
            ],
        ),
        migrations.CreateModel(
            name='MandateRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date de Début de Mandat')),
                ('function', models.CharField(choices=[('CHAIR', 'Président'), ('VCHAIR', 'Vice-Président'), ('COUNS', 'Conseiller'), ('UNK', 'Non Renseigné')], default='UNK', max_length=6, verbose_name='Fonction Occupée')),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officials.official')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.region')),
            ],
        ),
        migrations.CreateModel(
            name='MandateDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date de Début de Mandat')),
                ('function', models.CharField(choices=[('CHAIR', 'Président'), ('VCHAIR', 'Vice-Président'), ('COUNS', 'Conseiller'), ('UNK', 'Non Renseigné')], default='UNK', max_length=6, verbose_name='Fonction Occupée')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.department')),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officials.official')),
            ],
        ),
        migrations.CreateModel(
            name='MandateCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date de Début de Mandat')),
                ('function', models.CharField(choices=[('CHAIR', 'Président'), ('VCHAIR', 'Vice-Président'), ('COUNS', 'Conseiller'), ('UNK', 'Non Renseigné')], default='UNK', max_length=6, verbose_name='Fonction Occupée')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.city')),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officials.official')),
            ],
        ),
    ]
