# Generated by Django 3.1.5 on 2021-05-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0003_auto_20210516_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='official',
            name='mandate_city',
        ),
        migrations.AddField(
            model_name='official',
            name='mandate_city',
            field=models.ManyToManyField(blank=True, null=True, to='officials.MandateCity'),
        ),
        migrations.RemoveField(
            model_name='official',
            name='mandate_department',
        ),
        migrations.AddField(
            model_name='official',
            name='mandate_department',
            field=models.ManyToManyField(blank=True, null=True, to='officials.MandateDepartment'),
        ),
        migrations.RemoveField(
            model_name='official',
            name='mandate_intercom',
        ),
        migrations.AddField(
            model_name='official',
            name='mandate_intercom',
            field=models.ManyToManyField(blank=True, null=True, to='officials.MandateInterCom'),
        ),
        migrations.RemoveField(
            model_name='official',
            name='mandate_region',
        ),
        migrations.AddField(
            model_name='official',
            name='mandate_region',
            field=models.ManyToManyField(blank=True, null=True, to='officials.MandateRegion'),
        ),
        migrations.RemoveField(
            model_name='official',
            name='national_mandate',
        ),
        migrations.AddField(
            model_name='official',
            name='national_mandate',
            field=models.ManyToManyField(blank=True, null=True, to='officials.NationalMandate'),
        ),
    ]
