# Generated by Django 3.1.5 on 2021-05-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0003_auto_20210523_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='mandate_city',
            field=models.ManyToManyField(blank=True, to='officials.MandateCity', verbose_name='Mandats Municipaux'),
        ),
        migrations.AlterField(
            model_name='official',
            name='mandate_department',
            field=models.ManyToManyField(blank=True, to='officials.MandateDepartment', verbose_name='Mandat de Conseiller Départemental'),
        ),
        migrations.AlterField(
            model_name='official',
            name='mandate_intercom',
            field=models.ManyToManyField(blank=True, to='officials.MandateInterCom', verbose_name='Mandats Intercommunaux'),
        ),
        migrations.AlterField(
            model_name='official',
            name='mandate_region',
            field=models.ManyToManyField(blank=True, to='officials.MandateRegion', verbose_name='Mandat de Conseiller Régional'),
        ),
        migrations.AlterField(
            model_name='official',
            name='mp_mandate',
            field=models.ManyToManyField(blank=True, to='officials.MPMandate', verbose_name='Mandat de Député'),
        ),
        migrations.AlterField(
            model_name='official',
            name='propinquity_level',
            field=models.CharField(choices=[('0-PROPINQ', 'Idées incompatibles'), ('1-PROPINQ', 'Idées presque compatibles'), ('2-PROPINQ', 'Idées compatibles'), ('3-PROPINQ', 'Idées proches'), ('4-PROPINQ', 'Mêmes idées'), ('UNK-PROPINQ', 'Idées inconnues')], default='UNK-PROPINQ', max_length=11, verbose_name='Proximité'),
        ),
        migrations.AlterField(
            model_name='official',
            name='senator_mandate',
            field=models.ManyToManyField(blank=True, to='officials.SenatorMandate', verbose_name='Mandat de Sénateur'),
        ),
    ]
