# Generated by Django 3.1.5 on 2021-05-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0003_auto_20210515_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandatedepartment',
            name='function',
            field=models.CharField(choices=[('Président', 'Président'), ('Vice-Président', 'Vice-Président'), ('Conseiller', 'Conseiller'), ('UNK', 'Non Renseigné')], default='UNK', max_length=14, verbose_name='Fonction Occupée'),
        ),
    ]
