# Generated by Django 3.1.5 on 2021-06-02 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0004_auto_20210529_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='official',
            name='influence_level',
        ),
        migrations.RemoveField(
            model_name='official',
            name='propinquity_level',
        ),
    ]
