# Generated by Django 3.1.5 on 2021-05-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0005_auto_20210516_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='mandate_city',
            field=models.ManyToManyField(blank=True, to='officials.MandateCity'),
        ),
        migrations.AlterField(
            model_name='official',
            name='mandate_department',
            field=models.ManyToManyField(blank=True, to='officials.MandateDepartment'),
        ),
        migrations.AlterField(
            model_name='official',
            name='mandate_intercom',
            field=models.ManyToManyField(blank=True, to='officials.MandateInterCom'),
        ),
        migrations.AlterField(
            model_name='official',
            name='mandate_region',
            field=models.ManyToManyField(blank=True, to='officials.MandateRegion'),
        ),
        migrations.AlterField(
            model_name='official',
            name='national_mandate',
            field=models.ManyToManyField(blank=True, to='officials.NationalMandate'),
        ),
    ]
