# Generated by Django 3.1.5 on 2021-05-20 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        ('officials', '0006_auto_20210516_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPMandate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date de Début de Mandat')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.department')),
            ],
        ),
        migrations.CreateModel(
            name='SenatorMandate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date de Début de Mandat')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.department')),
            ],
        ),
        migrations.RemoveField(
            model_name='official',
            name='national_mandate',
        ),
        migrations.DeleteModel(
            name='NationalMandate',
        ),
        migrations.AddField(
            model_name='official',
            name='mp_mandate',
            field=models.ManyToManyField(blank=True, to='officials.MPMandate'),
        ),
        migrations.AddField(
            model_name='official',
            name='senator_mandate',
            field=models.ManyToManyField(blank=True, to='officials.SenatorMandate'),
        ),
    ]
